# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_docs', models.IntegerField(blank=True, null=True)),
                ('in_degree', models.IntegerField(blank=True, null=True)),
                ('out_degree', models.IntegerField(blank=True, null=True)),
                ('starting_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indexing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
