# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0003_auto_20160130_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexing',
            name='direction',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
