# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0004_auto_20160130_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clustering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
