# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0005_clustering'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha', models.FloatField()),
                ('threshold', models.IntegerField()),
            ],
        ),
    ]
